### PR TITLE
Add API endpoint to GET assets for a specified collection and tag - issue 131

### PR DESCRIPTION
**Pull request by asimonw**
This should be tested along with issue 129.
No unit tests written yet.

### CODE REVIEW

**Comment by georgemillard** [comment]
Hi @asimonw, I have tested both of these and all looks good!

My only request would be a change of variable name from col_id to collection_id. I have tried to keep variable names as clear as possible throughout the DAM code. I don't think it would make a noticeable performance difference, and once we find a good python minifier this won't be an issue. 

Something we may want to think about is a code style guide to keep our code as consistent as our design.

**Comment by asimonw** [comment]
@georgemillard Happy to make that change. I don't think a few characters makes much of a difference, really. It's not like code which needs to be optimised for the browser.

**Comment by asimonw** [comment]
@georgemillard Updated the variable name now. Some lines will be too long for PEP8 standards now, I think, but we can tackle that when we introduce a linting step?

**Comment by georgemillard** [comment]
Sounds good to me!

**Pull request merged**
