### PR TITLE
#194 Filters are now collapsable 

### PR DESCRIPTION
**Pull request by MertonL**

### CODE REVIEW

**Comment by georgemillard** [comment]
Hi Mert, nice show/hide implementation. What do you think about hidden by default? 

Stretch goal - a way to indicate which filters are applied when you are viewing this default "hidden" list eg. Titles are bold, or highlighted blue in the same way that selected individual filters are.

**Comment by georgemillard** [comment]
Another possibility if you don't like hide by default would be show by default but only show first 5 options, then "see more"

**Comment by MertonL** [comment]
@georgemillard I have updated the filters so that they now hide by default. 
Also when hidden, if a filter is selected, they will display bold and blue indicating that there is something selected inside. 
Please test and if you think that the "see more" option would be more useful let me know and i'll implement it.

**Comment by MertonL** [comment]
I have noticed an issue that on other pages that uses the filter widget, it is not displaying/working correctly. Assuming we want it to be a feature on all pages that use filters, I will look into fixing this.

**Comment by georgemillard** [comment]
I am having a problem with the js for filters not working when the js files are referenced from filter.html. I'll look into it.

**Comment by georgemillard** [comment]
Updated to fix references to filter.js 
Back to you @MertonL!

**Pull request merged**
