### PR TITLE
Feature 229 list page

### PR DESCRIPTION
**Pull request by asimonw**
@MertonL Would you have some time today to review this? Let me know if not.

The main notable thing is that I created a custom filter to be able to dynamically get values from a dict in templates directly.

### CODE REVIEW

**Comment by MertonL** [comment]
Hey @asimonw checking it now and I'm getting some weird layout issues and "None" appears in the list also. The order and grouping of the assets looks good however.
screen shot 2018-03-07 at 13 03 57

**Comment by MertonL** [comment]
Hey @asimonw, checking it now and the layout of the Assets on the topic pages seems to be misaligned (Always the first 2 assets), and "None" appears in the list also. Tested with and without gulp running.
The order and grouping of the assets all looks good though.
screen shot 2018-03-07 at 13 17 20

**Comment by asimonw** [comment]
@MertonL I assume that that's because you have some assets with no content type specified?
As I mentioned, the content type issue still needs to be cleared up. One thing we could already do is give it a default value of "Other." The layout issue could be related, but maybe you didn't clear your cache?

**Comment by asimonw** [comment]
@MertonL I did manage to reproduce the layout issue and found something else.. something funny about the `regroup` tag not working as you'd expect it to.. Will work on that, cheers.

**Comment by asimonw** [comment]
Hey, @MertonL the layout issue should be fixed now. I also made sure (I hope) that things are properly sorted by `type_field`.

**Comment by MertonL** [comment]
Cool @asimonw , that seems to have fixed the issues! I've updated my dummy assets script to add a content type and it now groups them nicely by type. 
I didn't know about the regroup tag before you used it, and reading up on it the data does need to be sorted otherwise it doesn't group correctly. 
Another solution Django suggests is to sort them (by content type) in the view first, but I think a dictsort in the template is a good solution for now. 
Will merge and close this PR.

**Comment by asimonw** [comment]
@MertonL Thanks, sorting in the view first might indeed be more performant. Let's keep that in mind, especially if we find that the page is a bit slow.

**Pull request merged**
