### PR TITLE
Feature 274 search

### PR DESCRIPTION
**Pull request by asimonw**
Would be nice to already put this on staging to test performance and effectiveness of the solution so far. 

Some caveats will be outlined in the issue #274

### CODE REVIEW

**Comment by MertonL** [comment]
Thanks @asimonw, As a first implementation of search, I think it works well and is immediately useful. 
The "stemming" you mentioned in (#274) works well and makes the results a lot more meaningful than if was simply taking the search phrase. 

If having `link` & `file` included in the search - especially files - is extra overhead, then maybe at this point it shouldn't be included, as the file is appended with the S3 folder and that isn't going to be something that people will or should know. 

So perhaps, switching them for `contributors` and `locations`, at this stage might be more useful to the users. If it works like that in terms of work load and performance.

**Comment by asimonw** [comment]
@MertonL I agree that removing `file` and `link` at this stage makes sense. I left them in there for now so guys could see it for yourselves.

If you're happy with that, I'd still like it if we could merge this in as it is, so that we can play with it on staging tomorrow. I'll swap `file` and `link` for `locations` and `contributors` when I add the last front-end bit tomorrow. WDYT?

**Comment by MertonL** [comment]
Great, thats fine with me!

**Comment by georgemillard** [comment]
On staging - looking good!

**Pull request merged**
