### PR TITLE
[#275] Updated spacing of the topic page items

### PR DESCRIPTION
**Pull request by MertonL**
Updated spacings as per discussion in issue-#275

### CODE REVIEW

**Comment by georgemillard** [comment]
@MertonL @asimonw 
Just had a chat with @MertonL about checking in build files for DAM user interface, as currently when I go to test a new branch, unless I make changes to a scss file myself before running gulp, my css files won't get updated. We could discuss this in our dev meeting later today.

**Comment by georgemillard** [comment]
Hey @asimonw, @MertonL and I have been discussing how to handle build files until we have a dedicated gulp build task. 

@MertonL suggests not checking in build files on any feature branch, and only checking them in after a feature has been merged into develop. This should maintain the continuity of build files on develop, avoiding merge conflicts. We have altered the gulpfile to handle building files if none are present.

So the process would be, pull down feature branch, run gulp, test, `git flow feature finish`, run `gulp` on develop, add build files here only, `git push`.

Would be great to get your thoughts!

**Comment by asimonw** [comment]
@georgemillard Sounds like that would mean that I'd need to deal with unstashed files which are also not in gitignore all the time. I know that that's how you guys work, but I like to keep my workspace as close to empty as possible. Remembering to add exactly the right files before a release is also a bit error prone (and tedious).

So a way around that could be to have a local `dev` folder and a `build` folder inside of the `static` folder. The `dev` folder would be in gitignore, so we never have to worry about that. What's in the `build` folder can then always be checked in, but would only be updated on `gulp build` which we would have to run before each release. The template could serve from `dev` or `build` depending on the `env` variable. What do you think?

**Comment by MertonL** [comment]
@asimonw That sounds like a more robust way of doing it, and keeps it inline with our other sites using `gulp build`. 

It might be possible to handle it all in the settings.py, which might be a tidy solution, something like this perhaps:
```
if (ENVIRONMENT != 'development'): 
    STATICFILES_LOCATION = 'static/build'
else:
    STATICFILES_LOCATION = 'static/dev'
```

**Comment by asimonw** [comment]
@MertonL That would be perfect! I assume that we'd like to handle the `test` case like production? (in which case your code would work)

**Comment by MertonL** [comment]
Good point, depends where we're running tests I suppose (Local & on feature branch / develop & Staging on develop). 

But yes, I think testing with production files would produce more accurate results

**Pull request merged**
